app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/home');
});

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------

Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
        require config('infyom.laravel_generator.path.api_routes');
    });
});

*/

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

// Registration Routes...
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::get('/home', 'HomeController@index');

Route::resource('obras', 'ObrasController');

Route::resource('obrasEtapas', 'ObrasEtapasController');

Route::resource('obrasObjetos', 'ObrasObjetosController');

Route::resource('obrasPresupuestos', 'ObrasPresupuestosController');

Route::resource('presupuestoEtapas', 'PresupuestoEtapasController');

Route::resource('presupuestoTipos', 'PresupuestoTiposController');

Route::resource('presupuestoDetalles', 'PresupuestoDetallesController');

Route::resource('presupuestoDetalleTipos', 'PresupuestoDetalleTipoController');

Route::resource('proyectos', 'ProyectosController');

Route::get('proyectos/{objeto_id}/{tipo_id}/{etapa_id?}', 'ProyectosController@objetosPrespuestos')->where('objeto_id', '[0-9]+');

Route::get('proyectos/presupuestodetalle/{id}', 'ProyectosController@presupuestoDetalle');

Route::post('api/proyectos/getData/{action}', 'ProyectosController@getData');

Route::post('api/proyectos/getDataDetalle/{action}', 'ProyectosController@getDataDetalle');

Route::post('api/proyectos/etapaPro', 'ProyectosController@etapaPro');

Route::post('api/proyectos/tipoPro', 'ProyectosController@tipoPro');

/*
Route::get('obrasJson/obrasJson', 'ObrasController@obrasJson');
*/

app/Http/Controllers/ProyectosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Models\ObrasPresupuestos;
use App\Models\PresupuestoTipos;
use App\Models\PresupuestoDetalles;
use App\Models\PresupuestoEtapas;
use App\Http\Requests\CreateObrasRequest;
use App\Http\Requests\UpdateObrasRequest;
use App\Repositories\ObrasRepository;
use App\Repositories\ObrasObjetosRepository;
use App\Repositories\PresupuestoTiposRepository;
use App\Repositories\ObrasPresupuestosRepository;
use App\Repositories\PresupuestoEtapasRepository;
use App\Http\Controllers\AppBaseController as InfyOmBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class ProyectosController extends InfyOmBaseController
{
    /** @var  ObrasRepository */
    private $obrasRepository;
    private $obrasObjetosRepository;
    private $presupuestoTiposRepository;
    private $obrasPresupuestosRepository;
    private $presupuestoEtapasRepository;

    public function __construct(ObrasRepository $obrasRepo, ObrasObjetosRepository $obrasObjetosRepo, PresupuestoTiposRepository $presupuestoTiposRepo, ObrasPresupuestosRepository $obrasPresupuestosRepo, PresupuestoEtapasRepository $presupuestoEtapasRepo)
    {
        $this->middleware('auth');
        $this->obrasRepository = $obrasRepo;
        $this->obrasObjetosRepository = $obrasObjetosRepo;
        $this->presupuestoTiposRepository = $presupuestoTiposRepo;
        $this->obrasPresupuestosRepository = $obrasPresupuestosRepo;
        $this->presupuestoEtapasRepository = $presupuestoEtapasRepo;
    }

    /**
     * Display a listing of the Obras.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->obrasRepository->pushCriteria(new RequestCriteria($request));
        $obras = $this->obrasRepository->all();

        return view('proyectos.index')
            ->with('obras', $obras);
    }

    /**
     * Display the specified Obras.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $obras = $this->obrasRepository->findWithoutFail($id);

        if (empty($obras)) {
            Flash::error('Proyectos not found');
            return redirect(route('obras.index'));
        }
        
        $objetosObra = $obras->obrasObjetos;
        
        $presupuestoTipo = PresupuestoTipos::get();
        
        return view('proyectos.show')
            ->with('obras', $obras)
            ->with('presupuestoTipo', $presupuestoTipo)
            ->with('objetosObra', $objetosObra);
    }

    public function objetosPrespuestos($objeto_id, $tipo_id, $etapa_id = 0)
    {
        $dropDownTipoPresupuesto = $this->presupuestoTiposRepository->all();
        $dropDownEtapas = $this->presupuestoEtapasRepository->all();
        $obrasObjeto = $this->obrasObjetosRepository->findWithoutFail($objeto_id);
        $presupuestoTipo = $this->presupuestoTiposRepository->findWithoutFail($tipo_id);
        
        //dd($presupuestoTipo);
        
        if (empty($obrasObjeto)) {
            Flash::error('Obra Objetos not found');
            return redirect(route('proyectos.index'));
        }

        if (empty($presupuestoTipo)) {
            Flash::error('Presupuesto Tipo not found');
            return redirect(route('proyectos.index'));
        }
        
        return view('proyectos.objetosPrespuestos')
            ->with('obrasObjeto', $obrasObjeto)
            ->with('presupuestoTipo', $presupuestoTipo)
            ->with('dropDownTipoPresupuesto', $dropDownTipoPresupuesto)
            ->with('dropDownEtapas', $dropDownEtapas)
            ->with('etapa_id', $etapa_id)
            ->with('tipo_id', $tipo_id)
            ->with('objeto_id', $objeto_id);
    }
    
    public function presupuestoDetalle(Request $request, $id)
    {
        $masterPage = 'layouts.app';
        $esAjax = $request->ajax();
        if($esAjax == true){
            $masterPage = 'layouts.popup';
        }
       
        $obraPresupuesto = ObrasPresupuestos::find($id);
        
        return view('proyectos.presupuestoDetalle')
            ->with('masterPage', $masterPage)
            ->with('obraPresupuesto', $obraPresupuesto)
            ->with('presupuesto_id', $id);
    }
    
    public function etapaPro()
    {
        
        $data = PresupuestoEtapas::select('nombre as DisplayText','id as Value')->get();
        return Response::json(
            array(
                "Result"			=>		"OK",
                "Options"			=>		$data
            )
        );
            		
    }
    
    public function tipoPro()
    {
        
        $data = PresupuestoTipos::select('nombre as DisplayText','id as Value')->get();
        return Response::json(
            array(
                "Result"			=>		"OK",
                "Options"			=>		$data
            )
        );
            		
    }
    
    public function getData($action)
    {
       
        $mainTable = 'obras_presupuestos';
        $objeto_id = Request("objeto_id");
        $tipo_id = Request("tipo_id");
        $etapa_id = Request("etapa_id");
        $jtSorting = Request('jtSorting');
        $jtStartIndex = Request('jtStartIndex');
        $jtPageSize = Request('jtPageSize');
       	
        if(false){
             //prueba de variables recibida
            $testArray = array(
                "mainTable" 	=>	$mainTable,
                "objeto_id" 	=>	$objeto_id,
                "tipo_id" 	=>	$tipo_id,
                "etapa_id" 	=>	$etapa_id,
                "jtSorting" 	=>	$jtSorting,
                "jtStartIndex" 	=>	$jtStartIndex,
                "jtPageSize" 	=>	$jtPageSize
            );
        
            dd($testArray);
        }
        
    	switch ($action) 
    	{
    		case 'list':
              
                if($etapa_id > 0){
    				    $rows = ObrasPresupuestos::where([
                            ['obra_objeto_id',$objeto_id],
                            ['presupuesto_tipo_id',$tipo_id],
                            ['presupuesto_etapa_id',$etapa_id],
                        ])->count();
    			}else{
        				$rows = ObrasPresupuestos::where([
                            ['obra_objeto_id',$objeto_id],
                            ['presupuesto_tipo_id',$tipo_id],
                        ])->count();
    			}
                
                if (Request('jtSorting')) 
    			{
    				$search = explode(" ", Request("jtSorting"));
    				if($etapa_id > 0){
    				    $data = ObrasPresupuestos::where([
                            ['obra_objeto_id',$objeto_id],
                            ['presupuesto_tipo_id',$tipo_id],
                            ['presupuesto_etapa_id',$etapa_id],
                        ])
                        ->skip(Request("jtStartIndex"))
        				->take(Request("jtPageSize"))
        				->orderBy($search[0], $search[1])
        				->get();
    				}else{
        				$data = ObrasPresupuestos::where([
                            ['obra_objeto_id',$objeto_id],
                            ['presupuesto_tipo_id',$tipo_id],
                        ])
                        ->skip(Request("jtStartIndex"))
        				->take(Request("jtPageSize"))
        				->orderBy($search[0], $search[1])
        				->get();
    				}
    			
    			}
    			else
    			{
    			    if($etapa_id > 0){
    				    $data = ObrasPresupuestos::where([
                            ['obra_objeto_id',$objeto_id],
                            ['presupuesto_tipo_id',$tipo_id],
                            ['presupuesto_etapa_id',$etapa_id],
                        ])
                        ->skip(Request("jtStartIndex"))
        				->take(Request("jtPageSize"))
        				->get();
    				}else{
        				$data = ObrasPresupuestos::where([
                            ['obra_objeto_id',$objeto_id],
                            ['presupuesto_tipo_id',$tipo_id],
                        ])
                        ->skip(Request("jtStartIndex"))
        				->take(Request("jtPageSize"))
        				->get();
    				}
    			    
    			}
    			
    			return Response::json(
    				array(
    					"Result"			=>		"OK",
    					"TotalRecordCount"	=>		$rows,
    					"Records"			=>		$data,
    				)
    			);
    			
    		break;
    			
    		case 'create':

        		$item = new ObrasPresupuestos();
                $item->obra_objeto_id = Request("objeto_id");
                $item->presupuesto_tipo_id = Request("presupuesto_tipo_id");
                $item->presupuesto_etapa_id = Request("presupuesto_etapa_id");
                $item->codigo = Request("codigo");
                $item->unidad = Request("unidad");
                $item->descripcion = Request("descripcion");
                $item->precio = Request("precio");
                $item->cantidad = Request("cantidad");
                $item->Valor = $item->precio * $item->cantidad;
    			
    			if($item->save())
    			{
    				$toView = ObrasPresupuestos::find($item->id);
    				
    				return Response::json(array(
    						"Result"			=>		"OK",
    						"Record"			=>		$toView
    					)
    				);
    			}
    			
    		break;
    			
    		case 'update':

                $tempPrecio = Request("precio");
                $item = ObrasPresupuestos::find(Request("id"));
                
                if($tempPrecio < 0){
                    //$collection->sum('pages');
                    // $item->Valor = $item->precio * $item->cantidad;
                }else{
                    
                    $item->presupuesto_etapa_id = Request("presupuesto_etapa_id");
                    $item->codigo = Request("codigo");
                    $item->unidad = Request("unidad");
                    $item->descripcion = Request("descripcion");
                    $item->precio = Request("precio");
                    $item->cantidad = Request("cantidad");

resources/views/proyectos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Obras
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'obras.store']) !!}

                        @include('obras.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/proyectos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Obras
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($obras, ['route' => ['obras.update', $obras->id], 'method' => 'patch']) !!}

                        @include('obras.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/proyectos/fields.blade.php
<!-- Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id', 'Id:') !!}
    {!! Form::number('id', null, ['class' => 'form-control']) !!}
</div>

<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>

<!-- Descripcion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    {!! Form::text('descripcion', null, ['class' => 'form-control']) !!}
</div>

<!-- Obra Etapa Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('obra_etapa_id', 'Obra Etapa Id:') !!}
    {!! Form::number('obra_etapa_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('obras.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/proyectos/index.blade.php
@extends('layouts.app')

@section('content')

<section class="content-header">
	<h1 class="pull-left">
		Proyectos
		<small>
			<span class="label label-primary">{!! $obras->count() !!}</span> - Proyectos de Obras
		</small>
	</h1>
	<h1 class="pull-right">
	 	<a class="btn btn-primary" href="{!! route('obras.create') !!}">Add New</a>
	</h1>
</section>

<div class="clearfix"></div>
<div style="margin-top: 5px;">
	@foreach($obras as $obras)
		<div class="col-md-3 col-sm-6 col-xs-12">
			<a href="{!! route('proyectos.show', [$obras->id]) !!}">
				<div class="info-box">
					<span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>
					<div class="info-box-content">
						<span class="info-box-text"><b>{!! $obras->nombre !!}</b></span>
						<span class="info-box-text">{!! $obras->obrasEtapa->nombre !!}</span>
						<span class="info-box-text">{!! $obras->created_at !!}</span>
					</div>
					<!-- /.info-box-content -->
				</div>
			</a>
			<!-- /.info-box -->
		</div>
		<!-- /.col -->
	@endforeach
</div>

@endsection

resources/views/proyectos/objetosPrespuestos.blade.php
@extends('layouts.app')

@section('content')

<section class="content-header">
    <h1 class="pull-left">
        {!! $obrasObjeto->obra->nombre !!} > {!! $obrasObjeto->nombre !!} > {!! $presupuestoTipo->nombre !!}
    </h1>
</section>

<div class="clearfix"></div>

<div class="content">
    <div class="clearfix"></div>

    @include('flash::message')

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-body">
        
            <div class="col-sm-3" style="padding-left: 0px;">
                {!! Form::label('etapa_id','Etapa') !!}
                <select class="form-control" id="etapa_id" name="etapa_id">
                    <option value="0" @if(0 == $etapa_id) selected="selected" @endif>Seleccionar Etapa</option>
                    @forelse($dropDownEtapas as $etapa)
                        <option value="{{$etapa->id}}" 
                            @if($etapa->id == $etapa_id) selected="selected" @endif>
                            {{$etapa->nombre}}
                        </option>
                    @empty
                        <option value="">Seleccionar Etapa</option>
                    @endforelse
                </select>          <div class="clearfix"></div>
            </div>
            <div class="clearfix" style="margin-bottom: 15px;"></div>
            
            @include('proyectos.presupuestosJtable')
            
        </div>
    </div>
</div>

@endsection

resources/views/proyectos/presupuestoDetalle.blade.php
@extends($masterPage)

@section('content')
    <section class="content-header">
        <h1>
            Analisis de Costos de {!! $obraPresupuesto->descripcion !!}
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                      <!-- Nav tabs -->
                      <ul id="myTabs" class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab" title="Costo Directo de Materiales">Materiales</a></li>
                        <li role="presentation"><a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab" title="Costo Directo de Mano de Obra">Mano de Obra</a></li>
                        <li role="presentation"><a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab" title="Costo Directo de Equipos">Equipos</a></li>
                        <li role="presentation"><a href="#tab4" aria-controls="tab4" role="tab" data-toggle="tab" title="Costo Directo de Medios Auxiliares">Medios Auxiliares</a></li>
                      </ul>
                      <!-- Tab panes -->
                      <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="tab1">
                            <div id="DetalleMaterialesTableContainer"></div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab2">
                            <div id="DetalleManoDeObraTableContainer"></div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab3">
                            <div id="DetalleEquiposTableContainer"></div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab4">
                            <div id="DetalleAuxiliaresTableContainer"></div>
                        </div>
                      </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <button type="button" class="btn btn-primary" data-dismiss="modal" OnClick="updateDetalle('{!! $presupuesto_id !!}');">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style type="text/css">
        .modal-dialog {
            width: 900px;
        }
    </style>
@endsection

@section('scripts')

    <script>
        var presupuesto_id = "{!! $presupuesto_id !!}";
        var tokenValList1 = "{{csrf_token()}}";
        var tokenValCreate1 = "{{csrf_token()}}";
        var tokenValUpdate1 = "{{csrf_token()}}";
        var tokenValDelete1 = "{{csrf_token()}}";
        var tokenValEtapas1 = "{{csrf_token()}}";
    </script>
    
    <link href="{{ url('/Content/themes/metroblue/jquery-ui.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url('/Scripts/jtable/themes/metro/darkorange/jtable.min.css') }}" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{{ url('/Scripts/jquery-ui-1.11.4.min.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/jtable/jquery.jtable.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/jtable/localization/jquery.jtable.es.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/number_format.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/proyectos/detalle1Materiales.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/proyectos/detalle2ManoDeObra.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/proyectos/detalle3Equipos.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/proyectos/detalle4Auxiliares.js') }}"></script>
    
@endsection

resources/views/proyectos/presupuestosJtable.blade.php
<div id="ProyectosTableContainer"></div>

@section('scripts')

    <script>
        var tituloTabla = "{!! $obrasObjeto->obra->nombre !!} > {!! $obrasObjeto->nombre !!}";
        var objeto_id ="{!! $objeto_id !!}";
        var tipo_id="{!! $tipo_id !!}";
        var etapa_id="{!! $etapa_id !!}";
        var tokenValList = "{{csrf_token()}}";
        var tokenValCreate = "{{csrf_token()}}";
        var tokenValUpdate = "{{csrf_token()}}";
        var tokenValDelete = "{{csrf_token()}}";
        var tokenValEtapas = "{{csrf_token()}}";
    </script>
    
    <!--http://jtable.org/Content/themes/metroblue/jquery-ui.css-->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-bootstrap/0.5pre/assets/css/bootstrap.min.css">-->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.css">-->
    <!--<link href="{{ url('/Content/themes/custom-theme/jquery-ui-1.10.3.custom.css') }}" rel="stylesheet" type="text/css">-->
    <!--<link href="{{ url('/Scripts/jtable/themes/jqueryui/jtable_jqueryui.css') }}" rel="stylesheet" type="text/css">-->
    <!--<link href="{{ url('/Scripts/jtable/themes/metro/blue/jtable.min.css') }}" rel="stylesheet" type="text/css">-->
    <!--<link href="http://jtable.org/Content/themes/metroblue/jquery-ui.css" rel="stylesheet" type="text/css">-->
    <link href="{{ url('/Content/themes/metroblue/jquery-ui.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url('/Scripts/jtable/themes/metro/darkorange/jtable.min.css') }}" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{{ url('/Scripts/jquery-ui-1.11.4.min.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/jtable/jquery.jtable.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/jtable/localization/jquery.jtable.es.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/number_format.js') }}"></script>
    <script type="text/javascript" src="{{ url('/Scripts/proyectos/index.js') }}"></script>
    
@endsection

resources/views/proyectos/presupuestosTable.blade.php
<table class="table table-striped table-bordered" cellspacing="0" id="obrasPresupuestos-table">
   <thead>
        <tr>
            <th>Etapa</th>
            <th>Codigo</th>
            <th>Descripcion</th>
            <th>Unid/Med</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Valor</th>
        </tr>
    </thead>
    <tbody>
    @foreach($presupuestoLineas as $obrasPresupuestos)
        <tr>
            <td>{!! $obrasPresupuestos->presupuestoEtapa->nombre !!}</td>
            <td>{!! $obrasPresupuestos->codigo !!}</td>
            <td>{!! $obrasPresupuestos->descripcion !!}</td>
            <td>{!! $obrasPresupuestos->unidad !!}</td>
            <td>
                <!-- Button trigger modal -->
                <button type="button"  data-toggle="modal" data-target="#myModal">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    {!! $obrasPresupuestos->precio !!}
                </button>
            </td>
            <td>{!! $obrasPresupuestos->cantidad !!}</td>
            <td>{!! $obrasPresupuestos->Valor !!}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Materiales</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Material 1</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Material 1">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail2">Material 2</label>
                        <input type="text" class="form-control" id="exampleInputEmail2" placeholder="Material 2">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Material 3</label>
                        <input type="text" class="form-control" id="exampleInputEmail3" placeholder="Material 3">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail4">Material 4</label>
                        <input type="text" class="form-control" id="exampleInputEmail4" placeholder="Material 4">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
@section('scripts')
<script>

    $(document).ready(function () {
        $('#obrasPresupuestos-table').DataTable();
    });
</script>
<style>
    #obrasPresupuestos-table_length{
        display:none;
    }
</style>
@endsection

resources/views/proyectos/show.blade.php
@extends('layouts.app')

@section('content')

<section class="content-header">
    <h1 class="pull-left">
        {!! $obras->nombre !!}
        <small>
            <span class="label label-primary">{!! $objetosObra->count() !!}</span> - Objetos de Obra
        </small>

    </h1>
    <h1 class="pull-right">
        <a class="btn btn-primary" href="{!! route('obrasObjetos.create') !!}">Add New</a>
    </h1>
</section>
<div class="clearfix"></div>
<div style="margin-top: 5px;">
    @foreach($objetosObra as $objeto)
        <div class="col-md-3 col-sm-6 col-xs-12 ">
            <a href="{{ url('/proyectos/'.$objeto->id.'/1') }}" >
                <div class="info-box LinkAbajo1">
                    <span class="info-box-icon bg-yellow"><i class="ion ion-ios-gear-outline"></i></span>
                    <div class="info-box-content dropdown-toggle" data-toggle="LinkAbajo1">
                        <span class="info-box-text"><b>{!! $objeto->nombre !!}</b></span>
                        <span class="info-box-text">{!! $objeto->descripcion !!}</span>
                        <span class="info-box-text">{!! $objeto->created_at !!}</span>
                    </div>
                    <ul class="dropdown-menu subMenu1" style="display: none;">
                        <li><a href="#" style=" text-decoration: underline !important;">Tipo de Presupuesto</a></li>
                        @foreach($presupuestoTipo as $item)
                            <li><a href="{{ url('/proyectos/'.$objeto->id.'/'.$item->id ) }}">{!! $item->nombre !!}</a></li>
                        @endforeach
                    </ul>
                    <!-- /.info-box-content -->
                </div>
            </a>
            
            <!-- /.info-box -->
        </div>
        <!-- /.col -->
    @endforeach
</div>

@endsection

resources/views/proyectos/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $obras->id !!}</p>
</div>

<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('nombre', 'Nombre:') !!}
    <p>{!! $obras->nombre !!}</p>
</div>

<!-- Descripcion Field -->
<div class="form-group">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    <p>{!! $obras->descripcion !!}</p>
</div>

<!-- Obra Etapa Id Field -->
<div class="form-group">
    {!! Form::label('obra_etapa_id', 'Obra Etapa Id:') !!}
    <p>{!! $obras->obra_etapa_id !!}</p>
</div>